server:
  port: 8083
  compression:
    enabled: true
spring:
  pid:
    file: ${user.home}/.halo/application.pid
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

halo:
  cache: level